version: "3.6"
services:
# ----------------------------------------- Logion node 1 --------------------------------------------------------------
  private-database1:
    image: logionnetwork/logion-postgres:${PG_TAG:-latest}
    environment:
      - POSTGRES_PASSWORD=secret
  node1:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    environment:
      - NODE_KEY=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - CUSTOM_OPTIONS=--alice --no-mdns --ws-external --rpc-cors all
      - CHAIN_SPEC=test
  backend1:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - TYPEORM_HOST=private-database1
      - WS_PROVIDER_URL=ws://node1:9944
      - OWNER=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - DIRECTORY_URL=http://directory:8080
      - SMTP_ENABLED=false
    depends_on:
      - node1
      - private-database1
  frontend1:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:9944:9944
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - node1
    environment:
      - CERTBOT_EMAIL=user1@invalid.domain
      - BACKEND_HOST_PORT=backend1:8080
      - NODE_HOST_PORT=node1:9944
# ----------------------------------------- Logion node 2 --------------------------------------------------------------
  private-database2:
    image: logionnetwork/logion-postgres:${PG_TAG:-latest}
    environment:
      - POSTGRES_PASSWORD=secret
  node2:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    environment:
      - NODE_KEY=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      - CUSTOM_OPTIONS=--bob --no-mdns --bootnodes /dns4/node1/tcp/30333/p2p/12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2 --ws-external --rpc-cors all
      - CHAIN_SPEC=test
    depends_on:
      - node1
  backend2:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - JWT_SECRET=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      - JWT_ISSUER=12D3KooWQYV9dGMFoRzNStwpXztXaBUjtPqi6aU76ZgUriHhKust
      - TYPEORM_HOST=private-database2
      - WS_PROVIDER_URL=ws://node2:9944
      - OWNER=5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
      - DIRECTORY_URL=http://directory:8080
      - SMTP_ENABLED=false
    depends_on:
      - node2
      - private-database2
  frontend2:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 127.0.0.1:8081:80
      - 127.0.0.1:9945:9944
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend2
      - node2
    environment:
      - CERTBOT_EMAIL=user2@invalid.domain
      - BACKEND_HOST_PORT=backend2:8080
      - NODE_HOST_PORT=node2:9944
# ----------------------------------------- Logion directory --------------------------------------------------------------
  directory-database:
    image: postgres:12
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
  directory:
    image: logionnetwork/logion-directory:${DIRECTORY_TAG:-latest}
    ports:
      - 127.0.0.1:8090:8080
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - WS_PROVIDER_URL=ws://node1:9944
      - TYPEORM_HOST=directory-database
    depends_on:
      - node1
      - directory-database
