name: On push and PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
        matrix:
            step: ['test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: ${{ matrix.step }}
          run: |
            yarn install --immutable
            yarn ${{ matrix.step }}
