name: Build and tests
on:
  push:
    branches: [ main ]
    paths-ignore:
      - website/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - website/**

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.step }}
        run: |
          yarn install --immutable
          yarn build
          yarn test
